# 1/ Подтягивает последнюю версию образа сайта из GitHub Container Registry
# 2/ Пробрасывает порты 80, 443 (TCP и UDP)
# 3/ Монтирует два тома и директорию: один для данных сайта, второй для конфигурации, а директория для флагов
# 4/ Автоматически перезапускает контейнер в случае сбоя (если не остановлен вручную)

name: ecpsp-website

services:
    website:
        image: ghcr.io/kylichist/ecpsp-website:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ecpsp_website_data:/data
            - ecpsp_website_config:/config
            - ./flags:/srv/flags:ro

volumes:
    ecpsp_website_data:
    ecpsp_website_config:
