# Подтягивает последнюю версию образа сайта из GitHub Container Registry

name: ecpsp-website

services:
    website:
        image: ghcr.io/kylichist/ecpsp-website:latest
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
            - "443:443/udp"
        volumes:
            - ecpsp_website_data:/data
            - ecpsp_website_config:/config

volumes:
    ecpsp_website_data:
    ecpsp_website_config:
