name: Publish to GitHub Packages

on:
    push:
        tags:
            - 'v*'

run-name: ${{  github.ref_name }}

env:
    REGISTRY: ghcr.io
    IMAGE_NAME: ${{ github.repository }}

jobs:
    build-and-publish-image:
        runs-on: ubuntu-latest

        permissions:
            contents: read
            packages: write
            attestations: write
            id-token: write

        steps:
            -   name: Checkout repository
                uses: actions/checkout@v5.0.0

            -   name: Log in to the Container registry
                uses: docker/login-action@v3.5.0
                with:
                    registry: ${{ env.REGISTRY }}
                    username: ${{ github.actor }}
                    password: ${{ secrets.GITHUB_TOKEN }}

            -   name: Extract metadata (tags, labels) for Docker
                id: meta
                uses: docker/metadata-action@v5.8.0
                with:
                    images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                    tags: type=semver,pattern={{version}}

            -   name: Build and push Docker image
                id: push
                uses: docker/build-push-action@v6.18.0
                with:
                    context: .
                    push: true
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    build-args:
                        ENVIRONMENT=prod

            -   name: Generate artifact attestation
                uses: actions/attest-build-provenance@v2.4.0
                with:
                    subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
                    subject-digest: ${{ steps.push.outputs.digest }}
                    push-to-registry: true
